import test from 'node:test';import assert from 'node:assert/strict';
import {generateKeyPairSync,sign,randomUUID} from 'node:crypto';import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,readdirSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {main,dryRun} from './cli.mjs';import {MODEL,LIMITS,canonical,digest} from './policy.mjs';
const manifestRaw=readFileSync(new URL('./manifest.json',import.meta.url)),manifest=JSON.parse(manifestRaw),lock=JSON.parse(readFileSync(new URL('./package-identity.json',import.meta.url)));
const entry=process.env.WO75_PAN_ENTRY??'/private/tmp/wo75-work/consumer/node_modules/pan-agent/dist/index.js';
function fixture(){
 const root=mkdtempSync(join(process.env.WO75_TEST_ROOT??tmpdir(),'wo75-cli-')),home=join(root,'home'),state=join(home,'.local/state/pan-agent/wo75');mkdirSync(state,{recursive:true});
 const keys=generateKeyPairSync('ed25519'),sha='a'.repeat(40),secret='synthetic-'+randomUUID();
 writeFileSync(join(state,'authority.json'),JSON.stringify({publicKey:keys.publicKey.export({type:'spki',format:'pem'}),acceptedRunnerSha:sha}));
 const activation={authorized:true,runId:randomUUID(),humanAuthorizationId:'offline-fixture-only',notBefore:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+60000).toISOString(),binding:{runnerSha:sha,panHash:lock.package_sha256,manifestHash:digest(manifestRaw),model:MODEL,budget:LIMITS,taskIds:manifest.tasks.map(t=>t.id),images:Object.fromEntries(manifest.tasks.map(t=>[t.id,'sha256:'+'b'.repeat(64)]))}};
 const save=()=>{const {signature,...payload}=activation;activation.signature=sign(null,Buffer.from(canonical(payload)),keys.privateKey).toString('base64');writeFileSync(join(root,'activation.json'),JSON.stringify(activation));};save();
 const counts={credentials:0,dispatches:0,environments:0,verifiers:0},phases=[],seen=[];let turn=0,current;
 const dependencies={home,git:(_,args)=>args[0]==='rev-parse'?sha:'',credentialSource:()=>{counts.credentials++;return secret;},openBroker:({config})=>{counts.environments++;current=config.task.id;turn=0;seen.push(config);phases.push(current+':start');return {ready:Promise.resolve('Official fixture instruction '+current),async exec(command){phases.push(current+':tool');assert.equal(command,current==='break-filter-js-from-html'?'python /app/test_outputs.py':'pwd');return {status:'completed',exit_code:0,stdout:'fixture',stderr:''};},async quiesce(){return {confirmed:true};},async verify(){counts.verifiers++;phases.push(current+':verifier');return {status:'official_scored',rewards:{reward:0}};},async stop(){return {stopped:true};},async close(){phases.push(current+':close');}};},fetchImplementation:async(url,options)=>{counts.dispatches++;turn++;assert.equal(url,MODEL.endpoint);assert.equal(options.headers.authorization,'Bearer '+secret);const body=JSON.parse(options.body);assert(body.messages.some(m=>m.role==='user'&&m.content==='Official fixture instruction '+current));const command=current==='break-filter-js-from-html'?'python /app/test_outputs.py':'pwd';const delta=turn===1?{role:'assistant',reasoning_content:'synthetic-private',tool_calls:[{index:0,id:'call-'+current,type:'function',function:{name:'task_command',arguments:JSON.stringify({command,timeout:2})}}]}:{role:'assistant',content:'Completed.'};const frame=(delta,finish,usage)=>'data: '+JSON.stringify({object:'chat.completion.chunk',created:1,id:'reply',model:MODEL.model,choices:[{index:0,delta,finish_reason:finish}],...(usage?{usage:{prompt_tokens:5,completion_tokens:2,total_tokens:7}}:{})})+'\n\n';return new Response(frame(delta,null,false)+frame({},turn===1?'tool_calls':'stop',true)+'data: [DONE]\n\n');}};
 const args=['--activation',join(root,'activation.json'),'--entry',entry,'--task-root',join(root,'fake-source'),'--output',join(root,'output')];return {root,args,dependencies,activation,save,counts,phases,seen,secret};
}
const scan=root=>readdirSync(root,{withFileTypes:true}).map(p=>p.isDirectory()?scan(join(root,p.name)):readFileSync(join(root,p.name),'utf8')).join('\n');
test('Criteria1.1 real CLI reaches injected environments through signature/identity/package/ledger gates',async()=>{
 const f=fixture();const oldFetch=globalThis.fetch;globalThis.fetch=()=>{throw Error('real provider forbidden');};try{await main(f.args,f.dependencies);}finally{globalThis.fetch=oldFetch;}
 assert.deepEqual(f.counts,{credentials:10,dispatches:10,environments:5,verifiers:5});assert.deepEqual(f.seen.map(c=>c.task.id),manifest.tasks.map(t=>t.id));
 for(const id of manifest.tasks.map(t=>t.id))assert(f.phases.indexOf(id+':tool')<f.phases.indexOf(id+':verifier'));
 assert(!JSON.stringify(f.seen).includes(f.secret));const report=JSON.parse(readFileSync(join(f.root,'output/summary.json')));assert.equal(report.denominator,5);assert(report.rows.every(r=>r.state==='official_scored'&&r.reward.reward===0));
 await assert.rejects(main(f.args,f.dependencies),/EEXIST/);assert.equal(f.counts.dispatches,10);const artifacts=scan(f.root);assert(!artifacts.includes(f.secret));assert(!artifacts.includes('synthetic-private'));writeFileSync(join(f.root,'receipt.json'),JSON.stringify({counts:f.counts,phases:f.phases,canaryScan:'pass',realProvider:0,realCredential:0,realDocker:0}));
});
test('Criteria1.1 missing/invalid CLI authorization rejects before all injected effects',async()=>{
 for(const mutation of ['missing','unsigned','signature','expired','identity','budget','image']){const f=fixture();if(mutation==='missing')f.args=[];else if(mutation==='unsigned'){f.activation.authorized=false;f.save();}else if(mutation==='signature'){f.activation.signature='invalid';writeFileSync(f.args[1],JSON.stringify(f.activation));}else if(mutation==='expired'){f.activation.expiresAt=new Date(Date.now()-1).toISOString();f.save();}else if(mutation==='identity'){f.activation.binding.panHash='c'.repeat(64);f.save();}else if(mutation==='budget'){f.activation.binding.budget={...LIMITS,dispatchesPerTask:41};f.save();}else{f.activation.binding.images={};f.save();}await assert.rejects(main(f.args,f.dependencies));assert.deepEqual(f.counts,{credentials:0,dispatches:0,environments:0,verifiers:0});}
});
test('visible-test permission is limited to exact original file; image status remains unknown',()=>{
 const d=dryRun(),visible=d.tasks.filter(t=>t.officialVisibleTest);assert.equal(visible.length,1);assert.equal(visible[0].id,'break-filter-js-from-html');assert.equal(visible[0].officialVisibleTest.visible_path,'/app/test_outputs.py');assert.equal(visible[0].officialVisibleTest.git_blob_sha1,'1bf2128a002d4014d85094c2223f87c62ae9088d');assert.match(visible[0].officialVisibleTest.status,/unverified/);assert(d.tasks.every(t=>t.digest===null));assert.equal(d.authorized,false);assert.deepEqual(d.sideEffects,{credentials:0,provider:0,docker:0});
});
