import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,readdirSync,renameSync,statSync} from 'node:fs';
import {join} from 'node:path';import {spawnSync,spawn} from 'node:child_process';
import {archiveTask} from './full-durable.mjs';import {digest,canonical} from './policy.mjs';
const base=process.env.WO102_ROOT,external=process.env.WO102_EXTERNAL;assert(base&&external);mkdirSync(base,{recursive:true});mkdirSync(external,{recursive:true});
function setup(where){const root=mkdtempSync(join(base,'archive-')),archive=mkdtempSync(join(where,'destination-')),meta={campaignId:root.split('/').at(-1),identity:{mode:'offline-control'},durability:{archiveRoot:archive}},r={runId:'synthetic-run',task:'synthetic-task'};mkdirSync(join(root,'journal'));mkdirSync(join(root,'segments',r.runId,r.task),{recursive:true});writeFileSync(join(root,'campaign.json'),JSON.stringify(meta));writeFileSync(join(root,'segments',r.runId,r.task,'result.json'),'original');writeFileSync(join(root,'segments',r.runId,'ledger.jsonl'),'synthetic\n');return {root,archive,meta,r,target:join(archive,meta.campaignId,r.runId,r.task)};}
function store(c){return {root:c.root,meta:c.meta,head:digest(canonical(c.meta)),rows:[],add(event,data){this.rows.push({event,...data});}};}
const url=new URL('./full-durable.mjs',import.meta.url).href;
function command(c,crash){return `import {archiveTask} from ${JSON.stringify(url)};import {digest,canonical} from ${JSON.stringify(new URL('./policy.mjs',import.meta.url).href)};const c=${JSON.stringify(c)};const s={root:c.root,meta:c.meta,head:digest(canonical(c.meta)),rows:[],add(){}};archiveTask(s,c.r,stage=>{if(stage===${JSON.stringify(crash)})process.exit(73)});`;}
for(const where of [base,external])test('C-ARC-01 actual archive, duplicate and corruption '+where,()=>{const c=setup(where),s=store(c);if(where===external)assert.notEqual(statSync(base).dev,statSync(external).dev);archiveTask(s,c.r);const p=join(c.target,'commit/receipt.json'),bytes=readFileSync(p);archiveTask(s,c.r);assert.equal(s.rows.length,1);assert(readFileSync(p).equals(bytes));const receipt=JSON.parse(bytes);for(const [f,h] of Object.entries(receipt.files))assert.equal(digest(readFileSync(join(c.target,'snapshots',receipt.snapshot,f))),h);writeFileSync(join(c.root,'segments',c.r.runId,c.r.task,'result.json'),'conflict');assert.throws(()=>archiveTask(s,c.r),/archive_local_conflict/);assert(readFileSync(p).equals(bytes));});
for(const stage of ['copy','receipt_written','before_publish','after_publish','before_journal'])test('C-ARC-02 process death '+stage,()=>{const c=setup(external),p=spawnSync(process.execPath,['--input-type=module','-e',command(c,stage)],{encoding:'utf8'});assert.equal(p.status,73,p.stderr);assert.equal(readFileSync(join(c.root,'segments',c.r.runId,c.r.task,'result.json'),'utf8'),'original');const committed=existsSync(join(c.target,'commit/receipt.json'));assert.equal(committed,['after_publish','before_journal'].includes(stage));const s=store(c);archiveTask(s,c.r);assert.equal(s.rows.length,1);});
test('C-ARC-01 two independent concurrent publishers do not overwrite a committed directory',async()=>{const c=setup(external);const run=()=>new Promise(resolve=>{const p=spawn(process.execPath,['--input-type=module','-e',command(c,'none')],{stdio:['ignore','pipe','pipe']});let err='';p.stderr.on('data',b=>err+=b);p.on('close',code=>resolve({code,err}));});const results=await Promise.all([run(),run()]);assert(results.every(r=>r.code===0),JSON.stringify(results));const s=store(c);archiveTask(s,c.r);assert.equal(s.rows.length,1);});
test('C-ARC-02 unavailable, write/space failure and malformed published receipt stay closed',()=>{
 const c=setup(external),s=store(c);renameSync(c.archive,c.archive+'-held');assert.throws(()=>archiveTask(s,c.r),/archive_unavailable/);assert(!existsSync(c.archive));renameSync(c.archive+'-held',c.archive);
 for(const stage of ['copy','receipt_written','before_publish'])assert.throws(()=>archiveTask(s,c.r,x=>{if(x===stage)throw Object.assign(Error('injected ENOSPC'),{code:'ENOSPC'});}),/ENOSPC/);
 assert.equal(s.rows.length,0);archiveTask(s,c.r);const p=join(c.target,'commit/receipt.json');writeFileSync(p,'{partial');assert.throws(()=>archiveTask(store(c),c.r));
 const d=setup(external);mkdirSync(join(d.target,'commit'),{recursive:true});assert.throws(()=>archiveTask(store(d),d.r),/archive_incomplete_commit/);
});
test('C-ARC-01 missing archived file never confirms success',()=>{const c=setup(external),s=store(c);archiveTask(s,c.r);const p=JSON.parse(readFileSync(join(c.target,'commit/receipt.json'))),f=Object.keys(p.files)[0];renameSync(join(c.target,'snapshots',p.snapshot,f),join(c.target,'moved'));assert.throws(()=>archiveTask(store(c),c.r),/archive_inventory/);});

test('C-ARC-02 live archive refuses replacement mount on internal volume',()=>{const c=setup(base),s=store(c);s.meta.identity.mode='live';assert.throws(()=>archiveTask(s,c.r),/archive_not_external/);assert.equal(s.rows.length,0);});
