import test from 'node:test';import assert from 'node:assert/strict';
import {generateKeyPairSync,sign,randomUUID} from 'node:crypto';
import {mkdtempSync,readFileSync,readdirSync,mkdirSync,appendFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {MODEL,LIMITS,canonical,authorize,Ledger} from './policy.mjs';import {runAttempt} from './session.mjs';
const entry=process.env.WO75_PAN_ENTRY??'/private/tmp/wo75-work/consumer/node_modules/pan-agent/dist/index.js';
function signed(tasks,budget=LIMITS){const keys=generateKeyPairSync('ed25519');const binding={runnerSha:'a'.repeat(40),panHash:'b'.repeat(64),manifestHash:'c'.repeat(64),model:MODEL,budget,taskIds:tasks,images:{}};const activation={authorized:true,runId:randomUUID(),humanAuthorizationId:'synthetic-only',notBefore:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+60000).toISOString(),binding};activation.signature=sign(null,Buffer.from(canonical(activation)),keys.privateKey).toString('base64');return {activation,authority:{publicKey:keys.publicKey,acceptedRunnerSha:binding.runnerSha},binding};}
function wire(command,{missingUsage=false,reasoning='private-reasoning',text='Finished.'}={}){const delta=command?{role:'assistant',reasoning_content:reasoning,tool_calls:(Array.isArray(command)?command:[command]).map((cmd,index)=>({index,id:'tool-'+randomUUID(),type:'function',function:{name:'task_command',arguments:JSON.stringify(typeof cmd==='object'?cmd:{command:cmd,timeout:cmd==='sleep'?0.02:2})}}))}:{role:'assistant',reasoning_content:reasoning,content:text};const frame=x=>'data: '+JSON.stringify({object:'chat.completion.chunk',created:1,...x})+'\n\n';return frame({id:'response',model:'k3-256k',choices:[{index:0,delta,finish_reason:null}]})+frame({id:'response',model:'k3-256k',choices:[{index:0,delta:{},finish_reason:command?'tool_calls':'stop'}],...(!missingUsage?{usage:{prompt_tokens:10,completion_tokens:4,total_tokens:14}}:{})})+'data: [DONE]\n\n';}
function scan(root){return readdirSync(root,{withFileTypes:true}).map(x=>x.isDirectory()?scan(join(root,x.name)):readFileSync(join(root,x.name),'utf8')).join('\n');}
async function execute({id='task-a',instruction='Original task instruction',command='pwd',missingUsage=false,oversize=false,cancel=false,credentialEcho=false,budget=LIMITS,providerFailure=false,loop=false,verifierError=false,dispatchTimeout=false,recover=false,globalDeadline=false,expire=false,stopFailure=false,cancelOnCompletion=false,echoOutput=false}={}){
 const base=process.env.WO75_TEST_ROOT??tmpdir();mkdirSync(base,{recursive:true});const root=mkdtempSync(join(base,'wo75-test-'));const signedInput=signed([id],budget);const abort=new AbortController();let now=Date.now();const gate=authorize(signedInput.activation,signedInput.authority,signedInput.binding,{signal:abort.signal,clock:()=>expire?now:Date.now()});const ledger=new Ledger(join(root,'ledger'),gate);
 const secret='synthetic-'+randomUUID(),reasoning='private-'+randomUUID();let credentials=0,dispatch=0;const calls=[],requests=[],phases=[];let resolveExec;
 const env={async quiesce(){resolveExec?.({status:'interrupted',exit_code:null,stdout:'',stderr:'',termination:{confirmed:true}});return {confirmed:true};},async exec(cmd){calls.push(cmd);phases.push('exec');if(expire)now+=120000;if(cancelOnCompletion)abort.abort();if(cancel){setTimeout(()=>abort.abort(),5);return await new Promise(r=>resolveExec=r);}if(cmd==='sleep'){if(globalDeadline)return await new Promise(r=>resolveExec=r);return {status:'timeout',exit_code:null,stdout:'before-timeout',stderr:'',termination:{confirmed:recover}};}return {status:'completed',exit_code:cmd==='exit 7'?7:0,stdout:echoOutput?secret:'result',stderr:''};},async stop(reason){phases.push('stop');if(stopFailure)throw Error('stop unavailable');resolveExec?.({status:reason,exit_code:null,stdout:'',stderr:reason});return {stopped:true};},async verify(){phases.push('verify');if(verifierError)throw Error('synthetic verifier failure');return {status:'official_scored',rewards:{reward:0}};}};
 const previous=globalThis.fetch;globalThis.fetch=()=>{throw new Error('real network forbidden');};
 try{const report=await runAttempt({entry,task:{id,config:{agent:{timeout_sec:globalDeadline?.3:5},verifier:{timeout_sec:5}}},instruction,output:join(root,'attempt'),environment:env,gate,ledger,credentialSource:()=>{credentials++;return secret;},signal:abort.signal,fetchImplementation:async(url,options)=>{
  dispatch++;assert.equal(url,MODEL.endpoint);assert.equal(options.headers.authorization,'Bearer '+secret);const events=readFileSync(ledger.path,'utf8');assert.equal(events.split('dispatch_reserved').length-1,dispatch);requests.push(JSON.parse(options.body));phases.push('fetch');
  if(dispatchTimeout)return await new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(Error('synthetic deadline')),{once:true}));
  if(providerFailure)return new Response('{}',{status:429});
  return new Response(oversize?'x'.repeat(LIMITS.responseBytes+1):wire((dispatch===1||loop)?(credentialEcho?secret:command):recover&&dispatch===2?'after-timeout':null,{missingUsage,reasoning}),{status:200});
 }});const artifacts=scan(root);assert(!artifacts.includes(secret));assert(!artifacts.includes(reasoning));if(process.env.WO75_TEST_ROOT)appendFileSync(join(base,'receipts.jsonl'),JSON.stringify({root,task:id,phases,credentials,dispatch,canaryScan:'pass',requestMessages:requests.map(r=>r.messages.filter(m=>m.role==='user'))})+'\n');return {report,calls,requests,phases,credentials,dispatch,ledgerRows:readFileSync(ledger.path,'utf8').trim().split('\n').map(JSON.parse)};}
 finally{globalThis.fetch=previous;ledger.close();}
}
test('two real installed Adapter/Session paths use differing instructions and response-derived commands',async()=>{
 for(const [id,instruction,command] of [['task-a','Instruction alpha','pwd'],['task-b','Instruction beta','exit 7']]){const r=await execute({id,instruction,command});assert.deepEqual(r.calls,[command]);assert.equal(r.dispatch,2);assert(r.requests[0].messages.some(m=>m.role==='user'&&m.content===instruction));assert.equal(r.requests[0].max_tokens,4096);assert(r.requests[1].messages.some(m=>m.role==='tool'&&m.content.includes(command==='exit 7'?'7':'result')));assert.equal(r.report.verifier.status,'official_scored');assert.equal(r.phases.at(-1),'stop');}
});
test('missing usage and response overflow stop without a tool or verifier',async()=>{for(const opts of [{missingUsage:true},{oversize:true}]){const r=await execute(opts);assert.equal(r.dispatch,1);assert.equal(r.calls.length,0);assert.equal(r.report.verifier,null);}});
test('credential echo is rejected before IPC or archive',async()=>{const r=await execute({credentialEcho:true});assert.equal(r.calls.length,0);assert.equal(r.report.stopReason,'credential_echo');});
test('timeout and cancel target the bound environment and skip verifier',async()=>{for(const options of [{command:'sleep'},{cancel:true}]){const r=await execute(options);assert(r.phases.includes('stop'));assert.equal(r.report.verifier,null);assert(r.report.stopReason);}});

test('rate limit consumes one dispatch; no retry, tool or verifier',async()=>{const r=await execute({providerFailure:true});assert.equal(r.dispatch,1);assert.equal(r.credentials,1);assert.equal(r.calls.length,0);assert.equal(r.report.stopReason,'rate_limit');assert.equal(r.report.verifier,null);});
test('oversized request rejected before credential; low dispatch budget ends incomplete',async()=>{const r=await execute({instruction:'x'.repeat(LIMITS.requestBytes+1)});assert.equal(r.dispatch,0);assert.equal(r.credentials,0);assert.equal(r.report.verifier,null);const capped=await execute({loop:true,budget:{...LIMITS,dispatchesPerTask:2}});assert.equal(capped.dispatch,2);assert.equal(capped.calls.length,2);assert.equal(capped.report.agentStatus,'incomplete');assert(capped.report.stopReason);assert.equal(capped.report.verifier.status,'official_scored');});
test('verifier exception retains completed Agent and known usage',async()=>{const r=await execute({verifierError:true});assert.equal(r.report.agentStatus,'completed');assert.equal(r.report.usage.length,2);assert.equal(r.report.verifier.status,'evaluation_error');});

test('full 40-dispatch attempt stops before a forty-first credential callback',async()=>{const r=await execute({loop:true});assert.equal(r.dispatch,40);assert.equal(r.credentials,40);assert.equal(r.report.agentStatus,'incomplete');assert.equal(r.report.verifier.status,'official_scored');});
test('tool arguments cannot override destination; dispatch deadline consumes no retry',async()=>{const r=await execute({command:{command:'pwd',timeout:2,container:'other'}});assert.equal(r.calls.length,0);const t=await execute({dispatchTimeout:true,budget:{...LIMITS,dispatchSeconds:1}});assert.equal(t.dispatch,1);assert.equal(t.report.verifier,null);});

test('model-visible timeout schema and actionable rejection preserve 30-second bound',async()=>{
 for(const timeout of [30,60,120]){const r=await execute({command:{command:'pwd',timeout}});const tool=r.requests[0].tools.find(x=>x.function.name==='task_command').function;assert.equal(tool.parameters.properties.timeout.maximum,30);assert.equal(tool.parameters.properties.timeout.exclusiveMinimum,0);assert.match(tool.description,/30/);
 if(timeout===30)assert.equal(r.calls.length,1);else{assert.equal(r.calls.length,0);assert(r.requests[1].messages.some(x=>x.role==='tool'&&x.content.includes('0 < timeout <= 30')));}}
});

test('actual Session executes exactly 80 tools and prevents tool 81 before environment effect',async()=>{const r=await execute({loop:true,command:['pwd','pwd']});assert.equal(r.calls.length,80);assert.equal(r.dispatch,40);assert.equal(r.report.verifier.status,'official_scored');});
test('one campaign ledger covers five actual Session/Adapter attempts at 40 each',async()=>{
 const root=mkdtempSync(join(process.env.WO75_TEST_ROOT??tmpdir(),'wo78-campaign-'));const ids=['a','b','c','d','e'];const f=signed(ids);const gate=authorize(f.activation,f.authority,f.binding);const ledger=new Ledger(join(root,'ledger'),gate);let dispatches=0,tools=0;
 const previous=globalThis.fetch;globalThis.fetch=()=>{throw Error('no real network');};
 try{for(const id of ids){let local=0;const report=await runAttempt({entry,task:{id,config:{agent:{timeout_sec:60}}},instruction:'Synthetic bounded fixture',output:join(root,id),gate,ledger,credentialSource:()=> 'synthetic-only',environment:{async exec(){tools++;return {status:'completed',exit_code:0,stdout:'ok',stderr:''};},async stop(){},async verify(){throw Error('must not verify');}},fetchImplementation:async()=>{local++;dispatches++;return new Response(wire('pwd'));}});assert.equal(local,40);assert.equal(report.agentStatus,'incomplete');assert.equal(report.verifier,null);}
 assert.equal(dispatches,200);assert.equal(tools,200);assert.throws(()=>ledger.reserve('a','dispatch'),/budget/);assert.equal(readFileSync(ledger.path,'utf8').split('dispatch_reserved').length-1,200);
 }finally{ledger.close();globalThis.fetch=previous;}
});

test('confirmed local timeout reaches installed Session next request and a distinct next command',async()=>{
 const r=await execute({command:'sleep',recover:true});assert.deepEqual(r.calls,['sleep','after-timeout']);assert.equal(r.dispatch,3);assert.equal(r.report.stopReason,null);assert.equal(r.report.effects[0].result.status,'timeout');assert(r.requests[1].messages.some(m=>m.role==='tool'&&m.content.includes('before-timeout')&&m.content.includes('timeout')));assert.equal(r.report.verifier.status,'official_scored');assert.equal(r.phases.at(-1),'stop');
});
test('official Agent deadline still closes recovery and no stop failure is called confirmed',async()=>{
 const r=await execute({command:'sleep',globalDeadline:true});assert.equal(r.calls.length,1);assert.equal(r.dispatch,1);assert.equal(r.report.stopReason,'agent_timeout');assert.equal(r.report.verifier.status,'official_scored');
 const u=await execute({command:'sleep',stopFailure:true});assert.equal(u.dispatch,1);assert.equal(u.report.stopConfirmed,false);assert.equal(u.report.verifier,null);
});

test('expiry and cancellation racing natural completion forbid next dispatch and settle once',async()=>{
 for(const options of [{expire:true},{cancelOnCompletion:true}]){const r=await execute(options);assert.equal(r.calls.length,1);assert.equal(r.report.effects.length,1);assert.equal(r.dispatch,1);assert.equal(r.report.verifier,null);assert(r.phases.includes('stop'));assert.equal(r.ledgerRows.filter(x=>x.event==='attempt_finished').length,1);}
});
test('tool output credential canary is scrubbed before model context and archive',async()=>{
 const r=await execute({echoOutput:true});assert(r.requests[1].messages.some(m=>m.role==='tool'&&m.content.includes('[REDACTED]')));assert.equal(r.ledgerRows.filter(x=>x.event==='tool_reserved').length,1);assert.equal(r.ledgerRows.filter(x=>x.event==='attempt_finished').length,1);
});
