import assert from 'node:assert/strict';
import {test} from 'node:test';
import {PassThrough} from 'node:stream';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DailyEditor,graphemes} from '../src/tui/daily-editor.ts';
import {DailyWorkspace} from '../src/tui/daily-workspace.ts';
import {createCompactPresentation} from '../src/tui/presentation.ts';
import type {TuiOptions} from '../src/tui/tui.ts';
const wait=async(fn:()=>boolean)=>{for(let i=0;i<200;i++){if(fn())return;await new Promise(r=>setTimeout(r,5));}assert.fail('barrier timeout');};
function fixture(workspace:string){const input=Object.assign(new PassThrough(),{isTTY:true,isRaw:false,setRawMode(value:boolean){this.isRaw=value;}}),output=Object.assign(new PassThrough(),{isTTY:true,columns:80,rows:24});output.resume();let admits=0,cancels=0;const presentation=createCompactPresentation();const session={cancel(){cancels++;},runTask(){admits++;return new Promise(()=>{});},close:async()=>{},contextMessageCount:0};const ui=new DailyWorkspace({input,output,workspace,presentation,session,model:'fixture',provider:'fixture'} as unknown as TuiOptions);return {ui,input,output,counts:()=>({admits,cancels})};}
test('C-TUI-A02 grapheme editing and 500-line draft remain exact through narrow wrapping',()=>{const e=new DailyEditor();e.insert('中e\u0301👩‍💻\n'+'next\n'.repeat(500));const original=e.text;for(const n of [37,77,117]){const v=e.visual(n);assert.ok(v.lines.length>=501);assert.equal(e.text,original);}e.caret='中e\u0301👩‍💻'.length;e.backspace();assert.ok(e.text.startsWith('中e\u0301\n'));e.move(-1);e.backspace();assert.ok(e.text.startsWith('e\u0301'));assert.deepEqual(graphemes('中e\u0301👩‍💻'),['中','e\u0301','👩‍💻']);});
test('C-TUI-A02 safe edit, busy Enter, cancellation once and unsupported viewport never admit',()=>{const f=fixture('/tmp');const u=f.ui;u.phase='idle';u.key(undefined,{ctrl:true,name:'v'});u.key('@',{name:'@'});u.key(undefined,{name:'return'});u.key(':exit',{});assert.equal(u.editor.text,'@\n:exit');assert.equal(u.picker,undefined);u.key(undefined,{name:'escape'});u.phase='running';u.key(undefined,{name:'return'});u.key(undefined,{ctrl:true,name:'c'});u.key(undefined,{ctrl:true,name:'c'});assert.deepEqual(f.counts(),{admits:0,cancels:1});assert.equal(u.editor.text,'@\n:exit');u.phase='idle';f.output.columns=30;u.key(undefined,{name:'return'});assert.deepEqual(f.counts(),{admits:0,cancels:1});});
test('C-TUI-A01 selection is inline and stale discovery/capture never overwrites cancelled state',async()=>{const root=await mkdtemp(join(tmpdir(),'wo47-state-'));await mkdir(join(root,'a'));await mkdir(join(root,'b'));await writeFile(join(root,'a/same.txt'),'first');await writeFile(join(root,'b/same.txt'),'second');const {ui}=fixture(root);ui.phase='idle';ui.editor.insert('review ');ui.key('@',{});ui.key(undefined,{name:'escape'});assert.equal(ui.editor.text,'review @');await new Promise(r=>setTimeout(r,20));assert.equal(ui.picker,undefined);ui.editor.insert(' ');ui.key('@',{});await wait(()=>!!ui.picker&&!ui.picker.loading);ui.key('a/',{});ui.key(undefined,{name:'return'});await wait(()=>!ui.picker);assert.equal(ui.selected[0]?.text,'first');assert.equal(ui.entries.length,0);ui.key(undefined,{ctrl:true,name:'p'});assert.ok(ui.overlay?.lines.includes('SHA-256 '+ui.selected[0]!.sha256));ui.key(undefined,{name:'escape'});assert.equal(ui.entries.length,0);});
test('C-TUI-A01 transcript focus selects tool items; overlay keys never admit or edit source',()=>{const f=fixture('/tmp');f.ui.phase='idle';f.ui.entries=[{role:'Tool',text:'read',status:'Returned'},{role:'Tool',text:'bash',status:'Returned'}];f.ui.key(undefined,{name:'tab'});assert.equal(f.ui.focus,'transcript');f.ui.key(undefined,{name:'down'});assert.equal(f.ui.toolCursor,1);f.ui.key(undefined,{name:'down'});assert.equal(f.ui.toolCursor,1);f.ui.key(undefined,{name:'return'});assert.match(f.ui.overlay!.title,/View only/);assert.deepEqual(f.counts(),{admits:0,cancels:0});});
test('C-TUI-A02 actual input parser buffers split UTF-8 and bracketed paste without interpreting commands',async()=>{const f=fixture('/tmp');f.ui.start();f.ui.phase='idle';const text='中e\u0301👩‍💻\n@file\n:exit',bytes=Buffer.from('\x1b[200~'+text+'\x1b[201~');for(const byte of bytes)f.input.write(Buffer.from([byte]));await wait(()=>f.ui.editor.text===text);assert.equal(f.ui.picker,undefined);assert.deepEqual(f.counts(),{admits:0,cancels:0});f.ui.dispose();assert.equal(f.input.isRaw,false);});
