#!/usr/bin/env python3
"""Freeze or verify the protocol-reliability-v1 corpus from real ReAct MVP Traces."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from workspace_agent_harness.protocol_reliability import extract_context_corpus


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RUN_ROOT = PROJECT_ROOT / ".runs" / "react-mvp-5"
DEFAULT_OUTPUT = (
    PROJECT_ROOT
    / "workspace_agent_harness"
    / "benchmark_configs"
    / "protocol-reliability-v1-contexts.json"
)
SOURCE_CONFIG_HASH = (
    "sha256:1803342999f4eb934aea5b1943e1def6797a649c72eef45b869c6f89f4250c29"
)
SOURCE_MANIFEST_HASH = (
    "sha256:7a3a153f888f602187e500ac2a693f786d0a5852391f736920354b41d998596a"
)
SELECTION_SEED = "workspace-agent-harness/protocol-reliability-v1/controls"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-root", type=Path, default=DEFAULT_RUN_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--verify",
        action="store_true",
        help="compare regenerated bytes with the existing frozen corpus",
    )
    args = parser.parse_args()
    corpus = extract_context_corpus(
        run_root=args.run_root,
        source_config_hash=SOURCE_CONFIG_HASH,
        source_manifest_hash=SOURCE_MANIFEST_HASH,
        selection_seed=SELECTION_SEED,
    )
    rendered = json.dumps(corpus, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    if args.verify:
        if not args.output.is_file():
            raise SystemExit(f"frozen corpus is missing: {args.output}")
        if args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit("frozen corpus differs from regenerated Trace corpus")
        print(corpus["content_hash"])
        return 0
    if args.output.exists():
        raise SystemExit(f"refusing to overwrite frozen corpus: {args.output}")
    args.output.write_text(rendered, encoding="utf-8")
    print(corpus["content_hash"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
